[2021-12-16 21:17:35,107] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,107] logger_util.py->logs line:72 [INFO] 接口名称：成功获取token鉴权码
[2021-12-16 21:17:35,108] logger_util.py->logs line:72 [INFO] 请求方式：get
[2021-12-16 21:17:35,108] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-16 21:17:35,108] logger_util.py->logs line:72 [INFO] 请求params参数：{'appid': 'wx8a9de038e93f77ab', 'secret': '8326fc915928dee3165720c910effb86', 'grant_type': 'client_credential'}
[2021-12-16 21:17:35,496] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'access_token'}]
[2021-12-16 21:17:35,497] logger_util.py->logs line:72 [INFO] 实际结果：{'access_token': '52_nLSLNdXAf0nxvLE6jsv2a9oI3mEJcjDs7G3XEp3LWJ_mFlmrIUS9ptnLAxrLRrKRAqAwVxcgnidkB2XK89joOcsr9IoTVYqEpYYQBLTFJDVPQwpsUwkL-iQk6oB4901y_68UGe06WaaWyBleKOSgADASWA', 'expires_in': 7200}
[2021-12-16 21:17:35,497] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:35,497] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:35,507] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,507] logger_util.py->logs line:72 [INFO] 接口名称：检查appid为空
[2021-12-16 21:17:35,507] logger_util.py->logs line:72 [INFO] 请求方式：get
[2021-12-16 21:17:35,508] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-16 21:17:35,508] logger_util.py->logs line:72 [INFO] 请求params参数：{'appid': '', 'secret': '8326fc915928dee3165720c910effb86', 'grant_type': 'client_credential'}
[2021-12-16 21:17:35,555] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 41002}]
[2021-12-16 21:17:35,556] logger_util.py->logs line:72 [INFO] 实际结果：{'errcode': 41002, 'errmsg': 'appid missing rid: 61bb3c6e-14ed5eb9-2ef6c67b'}
[2021-12-16 21:17:35,556] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:35,556] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:35,566] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,566] logger_util.py->logs line:72 [INFO] 接口名称：检查secret为空
[2021-12-16 21:17:35,567] logger_util.py->logs line:72 [INFO] 请求方式：get
[2021-12-16 21:17:35,567] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2021-12-16 21:17:35,567] logger_util.py->logs line:72 [INFO] 请求params参数：{'appid': 'wx8a9de038e93f77ab', 'secret': '', 'grant_type': 'client_credential'}
[2021-12-16 21:17:35,675] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 41004}]
[2021-12-16 21:17:35,675] logger_util.py->logs line:72 [INFO] 实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 61bb3c6e-50d5fa16-76f996a1'}
[2021-12-16 21:17:35,675] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:35,675] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:35,683] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,683] logger_util.py->error_log line:67 [ERROR] 一级关键字必须要包含：name,request,validate
[2021-12-16 21:17:35,684] logger_util.py->error_log line:67 [ERROR] 规范YAML测试用例standard_yaml异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 101, in standard_yaml
    error_log("一级关键字必须要包含：name,request,validate")
  File "E:\workspace\api_frame\commons\logger_util.py", line 68, in error_log
    raise Exception(message)
Exception: 一级关键字必须要包含：name,request,validate

[2021-12-16 21:17:35,878] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,881] logger_util.py->error_log line:67 [ERROR] 发送请求send_request异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 115, in send_request
    kwargs[key] = self.replace_value(value)
  File "E:\workspace\api_frame\commons\requests_util.py", line 44, in replace_value
    new_value = getattr(self.obj,func_name)(*args_value2)
  File "E:\workspace\api_frame\debug_talk.py", line 16, in read_extract_data
    return read_extract_yaml(key)
  File "E:\workspace\api_frame\commons\yaml_util.py", line 14, in read_extract_yaml
    return value[key]
KeyError: 'tag_id'

[2021-12-16 21:17:35,882] logger_util.py->error_log line:67 [ERROR] 规范YAML测试用例standard_yaml异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 115, in send_request
    kwargs[key] = self.replace_value(value)
  File "E:\workspace\api_frame\commons\requests_util.py", line 44, in replace_value
    new_value = getattr(self.obj,func_name)(*args_value2)
  File "E:\workspace\api_frame\debug_talk.py", line 16, in read_extract_data
    return read_extract_yaml(key)
  File "E:\workspace\api_frame\commons\yaml_util.py", line 14, in read_extract_yaml
    return value[key]
KeyError: 'tag_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 73, in standard_yaml
    res = self.send_request(name,method,url,**caseinfo['request'])
  File "E:\workspace\api_frame\commons\requests_util.py", line 138, in send_request
    error_log("发送请求send_request异常：%s" % str(traceback.format_exc()))
  File "E:\workspace\api_frame\commons\logger_util.py", line 68, in error_log
    raise Exception(message)
Exception: 发送请求send_request异常：Traceback (most recent call last):
  File "E:\workspace\api_frame\commons\requests_util.py", line 115, in send_request
    kwargs[key] = self.replace_value(value)
  File "E:\workspace\api_frame\commons\requests_util.py", line 44, in replace_value
    new_value = getattr(self.obj,func_name)(*args_value2)
  File "E:\workspace\api_frame\debug_talk.py", line 16, in read_extract_data
    return read_extract_yaml(key)
  File "E:\workspace\api_frame\commons\yaml_util.py", line 14, in read_extract_yaml
    return value[key]
KeyError: 'tag_id'


[2021-12-16 21:17:35,944] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:35,945] logger_util.py->logs line:72 [INFO] 接口名称：删除系统标签
[2021-12-16 21:17:35,945] logger_util.py->logs line:72 [INFO] 请求方式：post
[2021-12-16 21:17:35,946] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/delete?access_token=52_nLSLNdXAf0nxvLE6jsv2a9oI3mEJcjDs7G3XEp3LWJ_mFlmrIUS9ptnLAxrLRrKRAqAwVxcgnidkB2XK89joOcsr9IoTVYqEpYYQBLTFJDVPQwpsUwkL-iQk6oB4901y_68UGe06WaaWyBleKOSgADASWA
[2021-12-16 21:17:35,946] logger_util.py->logs line:72 [INFO] 请求json参数：{'tag': {'id': 1}}
[2021-12-16 21:17:36,170] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}]
[2021-12-16 21:17:36,170] logger_util.py->logs line:72 [INFO] 实际结果：{'errcode': 45058, 'errmsg': "can't modify sys tag hint: [ikHFf73Vf-1GTt_a] rid: 61bb3c6e-7f1545db-55addc0e"}
[2021-12-16 21:17:36,170] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:36,170] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:36,177] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:36,180] logger_util.py->logs line:72 [INFO] 接口名称：查询标签接口
[2021-12-16 21:17:36,180] logger_util.py->logs line:72 [INFO] 请求方式：get
[2021-12-16 21:17:36,180] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/get?access_token=52_nLSLNdXAf0nxvLE6jsv2a9oI3mEJcjDs7G3XEp3LWJ_mFlmrIUS9ptnLAxrLRrKRAqAwVxcgnidkB2XK89joOcsr9IoTVYqEpYYQBLTFJDVPQwpsUwkL-iQk6oB4901y_68UGe06WaaWyBleKOSgADASWA
[2021-12-16 21:17:36,364] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'tags'}]
[2021-12-16 21:17:36,365] logger_util.py->logs line:72 [INFO] 实际结果：{'tags': [{'id': 2, 'name': '星标组', 'count': 0}, {'id': 103, 'name': '\\u7801\\u5c1a\\u6559\\u80b220312', 'count': 0}, {'id': 113, 'name': '\\u7801\\u5c1a\\u6559\\u80b297938', 'count': 0}, {'id': 114, 'name': '\\u7801\\u5c1a\\u6559\\u80b230279', 'count': 0}, {'id': 151, 'name': '\\u7801\\u5c1a\\u6559\\u80b299551', 'count': 0}]}
[2021-12-16 21:17:36,365] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:36,365] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:36,372] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:36,373] logger_util.py->logs line:72 [INFO] 接口名称：查询标签接口
[2021-12-16 21:17:36,373] logger_util.py->logs line:72 [INFO] 请求方式：get
[2021-12-16 21:17:36,373] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/tags/get?access_token=52_nLSLNdXAf0nxvLE6jsv2a9oI3mEJcjDs7G3XEp3LWJ_mFlmrIUS9ptnLAxrLRrKRAqAwVxcgnidkB2XK89joOcsr9IoTVYqEpYYQBLTFJDVPQwpsUwkL-iQk6oB4901y_68UGe06WaaWyBleKOSgADASWA
[2021-12-16 21:17:36,565] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'tags'}]
[2021-12-16 21:17:36,565] logger_util.py->logs line:72 [INFO] 实际结果：{'tags': [{'id': 2, 'name': '星标组', 'count': 0}, {'id': 103, 'name': '\\u7801\\u5c1a\\u6559\\u80b220312', 'count': 0}, {'id': 113, 'name': '\\u7801\\u5c1a\\u6559\\u80b297938', 'count': 0}, {'id': 114, 'name': '\\u7801\\u5c1a\\u6559\\u80b230279', 'count': 0}, {'id': 151, 'name': '\\u7801\\u5c1a\\u6559\\u80b299551', 'count': 0}]}
[2021-12-16 21:17:36,566] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:36,566] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

[2021-12-16 21:17:36,574] logger_util.py->logs line:72 [INFO] ----------接口测试开始----------
[2021-12-16 21:17:36,575] logger_util.py->logs line:72 [INFO] 接口名称：文件上传接口
[2021-12-16 21:17:36,575] logger_util.py->logs line:72 [INFO] 请求方式：post
[2021-12-16 21:17:36,576] logger_util.py->logs line:72 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=52_nLSLNdXAf0nxvLE6jsv2a9oI3mEJcjDs7G3XEp3LWJ_mFlmrIUS9ptnLAxrLRrKRAqAwVxcgnidkB2XK89joOcsr9IoTVYqEpYYQBLTFJDVPQwpsUwkL-iQk6oB4901y_68UGe06WaaWyBleKOSgADASWA
[2021-12-16 21:17:36,576] logger_util.py->logs line:72 [INFO] 文件上传：{'media': <_io.BufferedReader name='E:\\shu.png'>}
[2021-12-16 21:17:37,376] logger_util.py->logs line:72 [INFO] 预期结果：[{'equals': {'status_code': 200}}, {'contains': 'url'}]
[2021-12-16 21:17:37,377] logger_util.py->logs line:72 [INFO] 实际结果：{'url': 'http://mmbiz.qpic.cn/mmbiz_png/gwVWn1TZHhX6YrD82JKbCZZIsFfb0KTEY4gkwWjLlsyns2ZUhibXnluibLJtj8enAopiaRhNTIJ8hH9udZPO0mD3A/0'}
[2021-12-16 21:17:37,377] logger_util.py->logs line:72 [INFO] 接口测试成功
[2021-12-16 21:17:37,377] logger_util.py->logs line:72 [INFO] ----------接口测试结束----------

